### ISSUE TITLE
Type

### ISSUE THREAD

**Issue by ogc-leedahl** [opengeospatial/oapi_common#1]
I don't disagree with collection/type or a registry but I do think we are going to have some confusion where types are going to be too generic.  Features/Geometries are items.  Is a tile a map tile, a vector tile or both? Is there a need for sub-types?

**Comment by cmheazel** [comment]
I believe this issue related to the structure of the /collections/{collectionId}/collection path.  There has been considerable work on that issue since February  (#74 ).  Recommend closure as a duplicate issue.
