### ISSUE TITLE
Definition of Heterogeneous

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#10]
In support of the discussions regarding heterogeneous vs. homogeneous collections, we need to document a definition for these terms.  That definition may be refined to be resource type specific where needed.

**Comment by joanma747** [comment]
This is important for the definition of layers. Reading the current WFS3.0 we have "datasets" and "collections". If we add WMS we will need to define "layers" as some renderization of features and coverages. If collections were heterogeneous collections and layers could be equivalent.

**Comment by cportele** [comment]
In my view one will typically split a dataset into collections for sharing features in the same way one would split it into layers for sharing maps.

**Comment by joanma747** [comment]
What is heterogeneous: 
Different FeatureTypes. 
Features+coverages
CRS+dimensions
Different styles applied
