### ISSUE TITLE
Use of `/api`

### ISSUE THREAD

**Issue by cportele** [opengeospatial/oapi_common#102]
This issue has been created as part of the [public review](https://www.ogc.org/standards/requests/203) and is based on [document 19-072](https://portal.ogc.org/files/91975). See in particular the Abstract and section 8.2.

`/api` should not be a mandatory path. If it is a mandatory path Features can not extend Common Core. Note that 8.2.2. does not require `/api`, so the existing mentions are probably outdated.

**Comment by cmheazel** [comment]
/api should not be a mandatory path.  This will be fixed.

**Comment by cmheazel** [comment]
In the current version (5/11/20) the path "/api" is not mandated.
Recommend that this issue be closed.
