### ISSUE TITLE
patternProperties

### ISSUE THREAD

**Issue by cportele** [opengeospatial/oapi_common#104]
This issue has been created as part of the [public review](https://www.ogc.org/standards/requests/203) and is based on [document 19-072](https://portal.ogc.org/files/91975). See in particular section 8.2.2.

Remove "patternProperties", it does not add anything and it is unclear what the special role of properties starting with "x-" is. "additionalProperties" uses the default and can be omitted, too.

**Comment by cmheazel** [comment]
PatternProperties element has been removed from landingPage.json.
