### ISSUE TITLE
Use of GeoJSON

### ISSUE THREAD

**Issue by cportele** [opengeospatial/oapi_common#108]
This issue has been created as part of the [public review](https://www.ogc.org/standards/requests/203) and is based on [document 19-072](https://portal.ogc.org/files/91975). See in particular sections 7.2, 8.5.5, and 10.3. 

Why does Common discuss GeoJSON and have a GeoJSON conformance class, where there are no requirements related to features in Common? In Common this probably should be a general JSON conformance class / discussion based on the current developer preference for JSON over other formats like XML.

**Comment by joanma747** [comment]
Agreed.

**Comment by jeffharrison** [comment]
Agreed.

**Comment by cmheazel** [comment]
Common Core now only defined HTML and JSON encodings.  Common Collections defines HTML, JSON and GeoJSON encodings.

**Comment by cmheazel** [comment]
Collection Information could be treated as a Feature.  The GeoJSON conformance class is included in /collections to support this option.

**Comment by joanma747** [comment]
I disagree. The collections path does not use "GeoJSON" but an specific schema of JSON to list the collections names and some of their properties. I only remember seeing GeoJSON in the "items" of a "collection" (OGC API Features). IMHO, the formulation of the `items' in a collection is out of scope of the OGC Common.

**Comment by dblodgett-usgs** [comment]
I would nuance this a bit -- it would be fine (preferable?) to have the collection json-schema be compatible with GeoJSON. But @joanma747 is right, bringing in the full generality of GeoJSON in common is too much.

**Comment by cmheazel** [comment]
Resolution - remove GeoJSON conformance class.

**Comment by cmheazel** [comment]
All GeoJSON requirements and tests have been removed from Part 2.

**Comment by jerstlouis** [comment]
@dblodgett-usgs to be clear, I don't think the collectionInfo schema is compatible with GeoJSON at all.
