### ISSUE TITLE
Terms from the OGC specification model

### ISSUE THREAD

**Issue by cportele** [opengeospatial/oapi_common#109]
This issue has been created as part of the [public review](https://www.ogc.org/standards/requests/203) and is based on [document 19-072](https://portal.ogc.org/files/91975). See clause 5.

* Remove all terms in clause 5 except "dataset" and "distribution".
* Maybe add a reference to 08-131 to the opening paragraph, but we should not list the definition of the terms of the OGC specification model in all OGC API standards.

**Comment by joanma747** [comment]
A definition of "collection" could also be appropiate given the fact that there is some confusion about the term outside the Features community. See https://github.com/opengeospatial/oapi_common/issues/47

**Comment by cmheazel** [comment]
As part of the final editorial cleanup, any term which is not used within the specification will be removed.

**Comment by cmheazel** [comment]
@cportele The terms from the specification model are commonly used incorrectly.  Re-stating these definitions helps to reduce miss-interpretation of the standard.

**Comment by cmheazel** [comment]
Issue #113 has been resolved in accordance with direction from the OAB.  That same resolution applies to this issue.
Recommend to be closed.
