### ISSUE TITLE
Example Landing Pages

### ISSUE THREAD

**Issue by jeffharrison** [opengeospatial/oapi_common#112]
OGC API - Common needs a site where sample Landing Pages are provided.

We are working on 3D Pilot and Participants would like to know if they are implementing OGC API - Common correctly.

My apologies if this exists and I missed it.

Thanks and Regards,
Jeff

**Comment by joanma747** [comment]
Some implementations of the OGC API Features are shown here:
https://github.com/opengeospatial/ogcapi-features/blob/master/implementations.md
There are at least 6 landing page URLs.

In common the landing page is very flexible. The only requirement is:
https://github.com/opengeospatial/oapi_common/blob/master/standard/requirements/core/REQ_root-success.adoc
(essentially it needs to link to 2-3 resources and the rest is open).

**Comment by jeffharrison** [comment]
Thanks!

Best Regards,
Jeff

**Comment by cportele** [comment]
You can also always go to the live services of the OGC API Features implementations that are passing the compliance test (see "live test" links):

https://www.ogc.org/resource/products/compliant?specid=1022

**Comment by jeffharrison** [comment]
Good stuff. Thank you!

3D Container Landing Pages should be coming online soon...

Best Regards,
Jeff
