### ISSUE TITLE
Is the Mod Spec Normative?

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#113]
Should 08-131 be listed as a Normative Standard?  On the portal it is listed under Policies and Procedures,

**Comment by cmheazel** [comment]
Per the OGC Architecture Board - July 14, 2020 (with some word-smithing)
1) Normative terms particular to the spec are listed in the front of the document
        examples: Collection, Web API 
2) Other terms are defined in a glossary annex 
        examples: Conformance class, requirements class
3) "With links internal and external to source spec."
        - Terms should be hyperlinked to their definition (as an aid to the user)
        - Definitions should include a hyperlink to the document where that term is defined.

API-Common Core has been re-organized to follow this guidance.

Recommend to be closed.

**Comment by joanma747** [comment]
We as a writers need to take care of the modular specification and not the implementors or this core. The OAB decided on incorporate the glossary of terms based on the mod spec. We can close the issue.
