### ISSUE TITLE
describedby instead of describedBy

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/oapi_common#114]
According to the [IANA Link Relation Types registry](https://www.iana.org/assignments/link-relations/link-relations.xml), a resource that provides information about the link's context must be indicated with the name `describedby`, instead of `describedBy`.

![image](https://user-images.githubusercontent.com/11427611/75674307-17ec7680-5c85-11ea-8c87-370b65096c4b.png)

![image](https://user-images.githubusercontent.com/11427611/77648353-4f8acd80-6f68-11ea-8116-adba9350a8a6.png)

According to https://github.com/opengeospatial/ogcapi-features/issues/338 this is an editorial fix.

**Comment by cmheazel** [comment]
Changes applied.
