### ISSUE TITLE
link relation type "data": clarification needed

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/oapi_common#115]
According to the spec, a link with link relation type "data" links to an information resource. But in OGC API - Features, a link with link relation type "data" links to the collection of collections, thus to a spatial resource.

![image](https://user-images.githubusercontent.com/11427611/77649054-709fee00-6f69-11ea-9bcc-443b7a2af7ca.png)

![image](https://user-images.githubusercontent.com/11427611/77649069-7695cf00-6f69-11ea-8330-2ec72e6ba8ae.png)

![image](https://user-images.githubusercontent.com/11427611/77649164-a47b1380-6f69-11ea-8eaf-4866c4ae6b0b.png)

![image](https://user-images.githubusercontent.com/11427611/77649180-acd34e80-6f69-11ea-8db2-db86618aa01e.png)

**Comment by cmheazel** [comment]
This may have been addressed when /Collections was broken out as a separate standard.  @cmheazel to verify.

**Comment by cmheazel** [comment]
All link relations are defined using the authoritative definitions from IANA and OGC. Discussion of Information resources will be removed.  The ATS has not been updated recently.  It is scheduled for update once we are sure there will be no further changes to the requirements.
Recommend to close.

**Comment by cmheazel** [comment]
The OGC policy for link relation types and the OGC link relation type repository resolves this issue.
Moved: @cmheazel 
Second: @cportele 
NOTUC
