### ISSUE TITLE
The term "resource" is used in an overly-abstract way.

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/oapi_common#119]
The term "_resource_" needs to be used plainly and accurately (that is, in a less abstract way).
 
[See text around table 1 of the abstract of OGC API Features for an example of how plainly it should be used.](http://docs.opengeospatial.org/is/17-069r3/17-069r3.html) 

There are 231 instances of the word _resource_ used in all kinds of abstract ways in the draft spec but only four resources ("/", "/api", "/conformance", "/collections") are currently described in the spec. 

There are three types of resource defined in section 8.1.1 that, to my mind, just confuse everything. 

From section 8.1.1:
> An OGC API provides a lighweight interface to access one or more resources. The resources addressed by OGC APIs fall into three categories: Foundation Resources, Spatial Resources, and Information Resources.

This taxonomy is wrong as soon as it is declared and un-needed to my mind. It's used very casually, but not always in the rest of the spec.

### Proposal:
Review and remove any abstract use of the word _resource_ that goes outside the scope of the resources that are part of the current core resources in table 1.

**Comment by dblodgett-usgs** [comment]
Discussion of this issue on the API-Common call today. 

No matter what, `Foundation Resources, Spatial Resources, and Information Resources.` need to be added to the definitions so people understand **how they help**.

We had further discussion around the issue of "resource" as an identifier versus a particular kind of content that you get from an identifier -- and the circularity of conversation / debate related to resources as an abstract concept. 

One proposal is to carefully define one _"Common Resource"_ type that would be a tightly-scoped api-common conformance paths and the formats (representations) that they can provide.

**Comment by dblodgett-usgs** [comment]
On API-Common call just now, we discussed removing reference to spatial and information resources given that they are rooted in "collections" which have been removed from core.

If and when that is merged, this issue can be closed.

**Comment by cmheazel** [comment]
"Resource" is to be defined in the Definitions section of API-Common core.  The definition is currently TBD.

**Comment by cmheazel** [comment]
The discussion of Spatial and Information Resources has been removed from Core.  Definitions for Spatial, Temporal, and Information Resources have been added to Collections where they may prove useful.

**Comment by dblodgett-usgs** [comment]
I'm happy. Thanks!
