### ISSUE TITLE
Collections - Sorenson

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#122]
Matt Sorenson: 
a. Given the constant churn in multiple hackathons, testbeds, and pilots, the use of collections seems confused and incomplete. While the document as written is clear, the in-progress implementations show that additional work to clarify and/or apply them is needed. This is especially true where multiple resources are involved (see specifically Testbed 15 OPF, Vector Tile Pilot, 3D Container Pilot) 
b. The list of collection types needs clarification based on in-progress implementations. Are Maps and Tiles spatial resources? How do you handle mixed collections (imagery tiles, vector tiles). If people trying to work with it are having problems, it needs to be revisited.

**Comment by lieberjosh** [comment]
Since "Collections" and "Collection" need to stand for very different resources in different API's, OGC API Common really has the choice of either not mandating this as part of Common (at least of a Core" or accepting that it must be used as a meaning-free placeholder.

**Comment by cmheazel** [comment]
OGC Common-Collections has been moved into a separate standard.  The resources returned by the /collections and /collections/{collectionId} requests have been re-named to be more descriptive of the resource.

**Comment by dblodgett-usgs** [comment]
This has been clarified in #140. Do we need to do anything else here? I'd say just close.

**Comment by cmheazel** [comment]
SWG agrees to close.
Moved: @cportele 
Second: @cmheazel 
NOTUC
