### ISSUE TITLE
CRS - Sorenson

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#125]
Matt Sorenson:
The discussion of CRS only covers how the the default is implemented. Additional instructions on how to extend or modify when needed would be helpful.

**Comment by cmheazel** [comment]
API-Common Part 3: Coordinate Reference Systems by Reference is a proposed module to address this issue. This is a slightly modified clone of the API-Features CRS extension.

**Comment by jyutzler** [comment]
We can close this, right?

**Comment by cmheazel** [comment]
Yes.
