### ISSUE TITLE
Extensibilty - Sorenson

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#127]
Matt Sorenson:
This is definitely an initial standard meant to expand as more APIs are implemented and new modules mature and are ready for reuse. The process for extension and addition is not well outlined in general terms. An API Developer Guide and module/extension registry would be useful.

**Comment by cmheazel** [comment]
A companion Best Practices document is planned, but little work has been done on it to-date.  An approach used in other OGC standards is to keep the Standard concise with embedded links into the Best Practices document.  This allows developers to rapidly access informative data as the need it, without cluttering up the Standard.  Recommend the same approach for API-Common.

**Comment by msorenson** [comment]
In this case, completing the best practices sooner would be better. Several of the points of contention for API-Common originate from the design to keep this sparse and allow modification and extension without providing the roadmap on how to do that. Absent that, you'll continue to get arguments on collections, tiles, CRS, and other resources where API-Common doesn't quite work for what a developer wants but could be extended but no guide to extensions or examples of practical extensions and applications are provided.

**Comment by cmheazel** [comment]
@msorenson An update:
Based on the feedback we have received, API-Common becomes a collection (set) of standards.  Each Common component will be documented as a separate Standard. API Standards developers can then pick the normative standards they need. Only API-Core is required.

**Comment by cmheazel** [comment]
@msorenson API-Common Collections has attempted to simplify the collections issue.  Comments welcome.

**Comment by jyutzler** [comment]
Can we close this one? It does not appear to me to be actionable.

**Comment by msorenson** [comment]
I have no problem closing this. It was more to keep the discussion going at the time and does not relate to a specific action for now.


Matt Sorenson

SETA Support (Strategic Alliance Consulting Inc.)

Systems and Acquisition Support Directorate

U.S. Army Geospatial Center

matthew.l.sorenson@usace.army.mil

msorenson@strategicaci.com

703-428-9173 (Desk)

571-218-7331 (Cell)


________________________________
