### ISSUE TITLE
Getting involved in OGC API-Common?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/oapi_common#129]
I heard there was a telecom on Monday? Nothing is listed in the portal and I can't find a API-Common SWG to join. There's nothing in the README of this repo about how to join official activities of the SWG either. Am I missing something?

**Comment by dblodgett-usgs** [comment]
I see some stuff now in "DEVELOPMENT.md" Is there a reason that content is not in the README?

When I sign the observer agreement, I get access denied -- I don't have sufficient permissions? Guessing that's why I can't see the project in the portal? Are others having this issue?

**Comment by uvoges** [comment]
Hi David,
Usually you can find it in the OGC Calendar. For the last telco it was: https://portal.ogc.org/index.php?m=calendar&a=view&event_id=65362
The next telco does not seem to be registered yet...

**Comment by cportele** [comment]
@dblodgett-usgs - There is no OGC API Common SWG, you still have to join the [old OWS Common SWG](https://www.ogc.org/projects/groups/owscommon1.2swg) - with a hopelessly outdated charter that lists 15 years old Change Requests like "WSDL Recommendations Annex" in its scope of work 😉.

**Comment by joanma747** [comment]
The group is called OWS Common 1.2 for historical reasons.

You should sign an observer agreement here (looks for the group in the long list)
https://portal.ogc.org/?m=public&orderby=default&tab=7
After that, everything will be visible to you.

If your problem is solved, please close the issue

**Comment by dblodgett-usgs** [comment]
Yeah -- I found that and signed but get:
![Screen Shot 2020-04-01 at 5 55 46 AM](https://user-images.githubusercontent.com/1492803/78129644-86843780-73dd-11ea-95ad-4aa556206963.png)

When trying to view the project.

**Comment by dblodgett-usgs** [comment]
fixed in 1d732b4b9da88e6bbaa3d268c5060fa4a508df72
