### ISSUE TITLE
API Resource Representation Model - OAB

### ISSUE THREAD

**Issue by percivall** [opengeospatial/oapi_common#130]
[OGC API Resource Representation Model (Collections, etc.)](https://portal.ogc.org/index.php?m=projects&a=view&project_id=228&tab=5&act=details&issue_id=1465) was discussed by the OAB on 2020-03-31.  This summary of the OAB discussion is provided for the SWG to consider in revision of the API Common spec:  

- Collection is to be an optional clause in API Common
-- This needs to be clarified in API Common
- API Building Blocks design pattern
-- Conformance class path lists the components available at a deployed API.   API implementation could include components from several API specs, e.g., Features, Coverages, EDR, Maps, Processing, etc.
-- Prepare a sequence diagram showing how a client uses the conformance path return (a list of URIs; paths and hyperlinks) and handles each resource type appropriately, e.g. [Feature/Coverage/Processing API Convergence](https://docs.google.com/presentation/d/1gMpGKc6JnsCHUATH21E1VWC-80ItvxMW8Wdkdhy4n-g/edit#slide=id.g7c491e0892_7_13) from January 2020 Sprint.
- Taxonomy of Resource Types
-- Define a taxonomy of resource types and clarify the aggregation of resources in API Common, e.g., [Resource Taxonomy]( https://portal.ogc.org/files/?artifact_id=92731) from June 2019 Sprint
-- What to call an aggregation of items?  Collection, container, 
-- Need to clarify what is a Geospatial Resource.

Also note the [OGC Policy Directive: 47](https://portal.ogc.org/public_ogc/directives/directives.php): paraphrased:  All OGC API SWGs will work on their respective standards with other SWGs; and report on that interaction using the template in advance of an OAB review.

**Comment by percivall** [comment]
A part of the discussion in the OAB was a list of references related to "Collections."  This list was not included in the summary, so it is provided here only as background and a personal contribution.

- Collection in OGC Baseline
-- ISO 19115-1:2013  - 4.4 dataset series - collection of datasets (4.3) sharing common characteristics
-- GML Version: 3.2.2 - 9.9.1 GML feature collections - A GML feature collection is a collection of GML feature instances.
-- [OpenSearch for EO - 4.1 Collection](http://docs.opengeospatial.org/is/13-026r8/13-026r8.html#5):  A Collection or a Dataset Series (in short Series) defines a container for a list of Products (or datasets) that have common properties. Products inherit all the Collection properties that are not explicitly overridden.
-- [SOSA SSN](www.w3.org/TR/vocab-ssn-ext/#sosa:ObservationCollection) - Collection of one or more observations, whose members share a common value for one or more property
- additionally
-- [STAC](github.com/radiantearth/stac-spec/tree/master/collection-spec)  ...the concept we are describing here, a set of assets that are defined with the same properties and share higher level metadata. Others called it: dataset series (ESA, ISO 19115), collection (CNES, NASA), dataset (JAXA), product (JAXA).
-- [THREDDS Catalog](https://www.unidata.ucar.edu/software/tds/current/catalog/InvCatalogSpec.html)  A dataset is direct if it contains at least one dataset access method, otherwise it is just a container for nested datasets, called a collection dataset.

**Comment by lieberjosh** [comment]
It is clear that different communities, domains, and applications use the term "Collection" refer to a set of one or more members, but differ on the characteristics of those members, the nature of membership, the characteristics common to all members, and acceptable relationships between collections. This suggests that API Common needs at least to allow for different collection types to specify clearly the above collection properties for a particular API purpose.

**Comment by dblodgett-usgs** [comment]
I'd like to propose that this issue is useful for reference but, now that collections is in a separate spec, this issue can probably be closed as "fixed".

**Comment by lieberjosh** [comment]
There still seem to be a couple of open OAB-type questions here:

-  To what extent does a common data resource concept (whether "collections" or something else) contribute to interoperability between different (OGC) API's?
- Can a "collections" concept be extended to provide semantic clarity across a range of data resources or is it just confusing outside of collections of features?

**Comment by dblodgett-usgs** [comment]
I totally agree that these issues remain -- but are they issues that block closing this particular issue? 

I believe @cmheazel is planning on using [his wiki post](https://github.com/opengeospatial/oapi_common/wiki/Resource-Path-Issue) to frame the this distinction that I understand to be 1) do we use collection items as a proxy for data catalog items? and/or 2) do we use `items` as a generic way to handle any-ol set of resources? I just feel like that debate would be better taken up in a dedicated issue -- that would probably reference @percivall's contributions above.

**Comment by dblodgett-usgs** [comment]
We've established an improved definition of Collection. We can close this now IMHO.
