### ISSUE TITLE
Consistently use hyphens in the URI segment that identifies the spec

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/oapi_common#138]
The [Conventions chapter](https://github.com/opengeospatial/oapi_common/blob/master/core/clause_6_conventions.adoc) says "The normative provisions in this draft standard are denoted by the URI http://www.opengis.net/spec/ogcapi-common/1.0."
  
However many of the Requirements Class URIs use an underscore instead of a hyphen e.g. 

http://www.opengis.net/spec/ogcapi_common/1.0/req/core

http://www.opengis.net/spec/ogcapi_common/1.0/req/html
 
Note as well that the Conformance Class URIs in Annex A use a hyphen.

http://www.opengis.net/spec/ogcapi-common/1.0/conf/core

The use of hyphens and underscores in the URI segment that identifies the spec should be consistent.

**Comment by cmheazel** [comment]
These should be:
http://www.opengis.net/spec/ogcapi-common-1/1.0 for Core and
http://www.opengis.net/spec/ogcapi-common-2/1.0 for Collections

**Comment by joanma747** [comment]
We will use this: http://www.opengis.net/spec/ogcapi-common-1/1.0
and an example is: http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core
Once applied we will close the issue.

**Comment by cmheazel** [comment]
Changed all cases of API_Common to API-Common.
(except for the GitHub path where it is correct).
