### ISSUE TITLE
Consistency in use of hyphens and colons in the title

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/oapi_common#139]
OGC 19-072 currently has the title "OGC API-Common Part 1: Core". The absence of a hyphen before the 'Part 1' makes it inconsistent with OGC 17-069r3 which has the title "OGC API - Features - Part 1: Core".

The title of OGC 19-072 should be changed to "OGC API - Common - Part 1: Core".

Please also check that the titles of the other Common parts follow the pattern.

**Comment by cmheazel** [comment]
Is this the official position of the OGC NA?

**Comment by joanma747** [comment]
We will use "OGC API - Common - Part 1: Core" to be consistent with ISO and OGC API - Features. We will close the issue when it is applied.

**Comment by ghobona** [comment]
Pull Request created with renaming fix https://github.com/opengeospatial/oapi_common/pull/141

**Comment by cmheazel** [comment]
Merged and closed.
