### ISSUE TITLE
Differences between "elements" and "essentials"

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/oapi_common#14]
I wonder if we have to consider the OGC essentials in the OWS Common of even if the "API elements" should be the essentials. 
See:
https://docs.opengeospatial.org/wp/16-019r4/16-019r4.html#_ogc_api_essentials

May be essentials are defined elsewhere and "elements" are defined here?. 
We need to clarify that

**Comment by cmheazel** [comment]
There are API modules which can be re-used in multiple API standards.  So I created a place in the OAPI Common GitHub to capture them.  Are they the same as the essentials?  That remains to be seen.  I expect that they will be identified as we build out the API standards.  And I expect they will include at least some of the API essentials.  But probably not all.
