### ISSUE TITLE
Merge API-Common and OWS Common SWGs?

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#145]
Add continued support for OWS Common to the new charter.  Look at Features, etc. for examples.

**Comment by ghobona** [comment]
Uploaded the draft charter to the Pending Documents register https://portal.ogc.org/files/?artifact_id=93956&version=1

The draft is currently worded such that the OGC API - Common SWG becomes a separate working group from the OWS Common SWG.

Once the OWS Common SWG has made a decision on whether to accept renaming to OGC API - Common SWG, we can then upload a revised version of the draft charter to the Pending Documents register.

**Comment by ghobona** [comment]
@cmheazel For the next telecon, please ask the SWG to confirm whether OGC API - Common SWG will be established as a new SWG or a renaming of the OWS Common SWG.

Please record the SWG decision in a Motion.

**Comment by cmheazel** [comment]
I suggest we follow the lead set by the API-Coverages [https://github.com/opengeospatial/ogc_api_coverages/blob/master/OGC-Coverages-SWG-Charter.html](Charter). This would establish the API-Common SWG as a re-chartering of the OWS-Common SWG. The scope would include all of the current work plus responsibility for the API-Common **family** of standards. 

One additional responsibility will be API-Common's central role in the API governance process.

**Comment by cmheazel** [comment]
The SWG has  been renamed, the charter approved, portal resources updated and e-mail reflector in the process of migration.
