### ISSUE TITLE
Clarify that Common can be extended.

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#146]
Add an explicit permission for derivative standards to extend Core.
See Features section 5.5.3 for an example.

**Comment by joanma747** [comment]
If we do not have something similar in core, consider including something based on: http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_references_to_openapi_components_in_normative_statements

**Comment by cmheazel** [comment]
API-Common Core explicitly states that it is expected to only be implemented with extensions. 
Recommend to close.

**Comment by joanma747** [comment]
The modular spec sets the rules for extensibility and by default you can extent.

We decided to close this issue with no objection.
