### ISSUE TITLE
OWS API Features has some issues that affects the core. Follow the link

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/oapi_common#15]
https://github.com/opengeospatial/WFS_FES/issues?q=is%3Aissue+is%3Aopen+label%3A%22OGC+API%3A+Core%22

In the future, we can open independent issues here for some (or all) of them in the future as needed.

**Comment by cmheazel** [comment]
OGC Features 1.0 is complete. The final specification has been reviewed for its impact and consistency with API Common.  This issue can be closed.
