### ISSUE TITLE
Name of Common Part 2

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#150]
Propose to change the name of Part 2 to OGC API Common Part 2: Geospatial Data.

To be put into a motion on July 6, 2020

**Comment by joanma747** [comment]
Motions
moved: jerome
second: @cportele 
NOTUC

WE will do the change.
We will cloe the issue once applied

**Comment by joanma747** [comment]
The change has been applied except in the name of the folder. This will happen after the sprint (s)
