### ISSUE TITLE
Motion to approve the charter for the group

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/oapi_common#156]
The OWS cannot set any requirement on other groups to use the outcome of OWS Common. There are other bodies to do that such as OAB and the API management to try to convince others groups to use it. Instead, the group have a mandate to detect "common" building blocks and to "centralize" them: "The primary goal of the Common API SWG is to serve as a coordinating body across the constellation of OGC Web API Standards. Part of that role is to identify API modules which may have common applicability to other OGC API standards and, where appropriate, mature those modules as additional parts of the Common API family of standards."

Can we develop a common set of requirements for security? Do we need to include anything on the charter. Do we need to include a "Part" on security.

The word "new" will be removed from the sentence "To ensure consistency across OGC API standards, a **new** multi-part standard called OGC API - Common will specify both mandatory and optional capabilities that all implementations of OGC API standards may support.". Other "new" occurrences will be analyzed.

MOTION: "The OWS Common SWG recommends the release of the charter document (currently in https://github.com/opengeospatial/oapi_common/tree/Charter/charter) for public comments."
* pending the Architecture DWG endorsement
* the charter branch will be merged with the master

Moved: Chuck Heazel
Second: David Blodgett
Discussion?
NOTUC

**Comment by ghobona** [comment]
Typo in the charter. It will be fixed before handing the document to the TC.

"**20-063r1**, OGC Web Service Common Implementation Specification standard"

Document number needs to be 06-121r9

Thanks @chris-little for spotting it.

**Comment by ghobona** [comment]
The Architecture DWG has now endorsed the proposed re-charter of the OWS Common SWG as the OGC API - Common SWG.

I will now hand the the draft charter over to @ogcscotts for the TC review.

**Comment by cmheazel** [comment]
Per Scott Simmons e-mail of October 2, 2020; the charter has been approved and portal resources updated.
