### ISSUE TITLE
clarify link href values

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/oapi_common#169]
It would be valuable to have clear, informative text on `link`object `href` properties, and what types of values are allowed.  Examples:

- fully qualified URL: `"href": "https://example.org/1/2/3.json"`
- relative URL: `"href": "1/2/3.json"`
- local/inline to the same document: `"href": "#/path/to/object"`

**Comment by cmheazel** [comment]
This informative text can be found in the API-Common Users Guide. A link to this document is provided in API-Common part 1 as part of the discussion of link relations (section 6.3).

**Comment by joanma747** [comment]
Guess that there a bullet missing in the list beginning 
* URI template
If that is the case we will reopen this.
WE decide to close it.
