### ISSUE TITLE
How to handle OWS common discussions that are happening in WFS 3.0?

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/oapi_common#20]
This OWS API common was initially a copy of the core part of WFS.
Discussions are happening in WFS that should be here of are affecting this piece. Example:
https://github.com/opengeospatial/WFS_FES/issues/30

How can we handle that?.
And what is worst: what will happen if WFS and this OWS common take incompatible decision?: We will end up in a OWS common that will never be accepted by the WFS community. Considering that WFS will not adopt OWS Common in its first version (or that is the intention today) this will be extremely confusing.

**Comment by cportele** [comment]
This is why we (the WFS SWG) asked for the joint hackathon and the "end of June" deadline for all key issues in Common so that we can synchronize before we finalize the Features draft.

**Comment by cmheazel** [comment]
That is also why I am working on both documents.

**Comment by cmheazel** [comment]
API-Features 1.0 is complete.  This issue is OBE.
