### ISSUE TITLE
Titles of OGC API standards and use in text

### ISSUE THREAD

**Issue by cportele** [opengeospatial/oapi_common#22]
The WFS SWG has decided to use the following title for the first part of the Features series:

"OGC API - Features - Part 1: Core"

This is consistent with the pattern discussed in the TC and the part notation aligns with the ISO notation for parts (e.g., ISO 19115-1 is "Metadata -- Part 1: Fundamentals"). 

This pattern represents the organisation where OGC API is a family of standards and there is a multi-part series for each resource type like 'Features' (or other aspects, like Common).
 
In normal text, however, the current idea is to not use dashes as it looks confusing to the readers. As an example, I have used "OGC API Features is comprised of multiple parts, each of them is a separate standard" or "This part of the OGC API Features standards is ..." and dropped the dash between "OGC API" and "Features" as it conflicts with the normal interpretation of dashes in sentences.

If there are any concerns about this approach, let us know as we should follow a consistent pattern.

**Comment by cmheazel** [comment]
Hearing no objections, I'll update OGC API-Common to follow this pattern.
