### ISSUE TITLE
OAPI common references an obsolete RFC

### ISSUE THREAD

**Issue by rmam-spinworks** [opengeospatial/oapi_common#23]
The [references section](https://github.com/opengeospatial/oapi_common/blob/master/OAPI-Common/clause_3_references.adoc) includes a reference to RFC5988.  However, that document was rendered obsolete in 2017 with RFC8288

https://tools.ietf.org/html/rfc8288

The updated RFC includes mostly clarifications and cleans up the document, thus possibly both documents may be interchangeable. Is there a reason to include a reference to the old RFC?

**Comment by cportele** [comment]
No, referencing an older version was not intentional, it is just the more well-known one.

I agree, we should reference RFC 8288.

**Comment by cmheazel** [comment]
Corrected
