### ISSUE TITLE
Question regarding the format used in the Landing page response document

### ISSUE THREAD

**Issue by rmam-spinworks** [opengeospatial/oapi_common#24]
I've noticed that the landing page response document example posted in [Requirement Class "Core"](https://github.com/opengeospatial/oapi_common/blob/master/OAPI-Common/clause_7_core.adoc) is quite similar to the [Hypertext Application Language](https://en.wikipedia.org/wiki/Hypertext_Application_Language) but with enough subtle differences to be incompatible. 

As far as I could tell, the only reference that's related with this topic is the [link headers recommendation](https://github.com/opengeospatial/oapi_common/blob/master/OAPI-Common/requirements/core/REC_link-header.adoc) which quotes RFC 5988. Is this format specified in some reference or is it an ad-hoc document format also specified by OAPI-Common?

**Comment by cmheazel** [comment]
The example landing page response document is JSON, not HTML.  It is also badly out of date (and wrong). That will be remedied shortly.
