### ISSUE TITLE
Modelling of links

### ISSUE THREAD

**Issue by ycespb** [opengeospatial/oapi_common#27]
Could it be considered to not have the "rel" property inside the "Link" object, but use it as the property name referring to an array of links ?  This would then be the same approach as used in https://docs.opengeospatial.org/is/14-055r2/14-055r2.html#91[OGC 14-055r2], OGC 17-003, OGC 17-047 etc.  The last two documents contain the corresponding JSON schema encoding..

Example:
----
		"links": {
			"profile": [
				{
					"href": "http://www.opengis.net/spec/owc-geojson/1.0/req/core"
				},
            {
					"href": "http://www.opengis.net/spec/os-geojson/1.0/req/core"
				}
			],
			"first": [
				{
					"href": "http://fedeo.esa.int/opensearch/request?&maximumRecords=10&query=ESA%20LDS&httpAccept=application/geo%2Bjson&platform=landsat&startRecord=1&status=2,0",
					"type": "application/geo+json",
					"title": "first results"
				}
			],
			"last": [
				{
					"href": "http://fedeo.esa.int/opensearch/request?&maximumRecords=10&query=ESA%20LDS&httpAccept=application/geo%2Bjson&platform=landsat&startRecord=1&status=2,0",
					"type": "application/geo+json",
					"title": "last results"
				}
			],
			"search": [
				{
					"href": "http://fedeo.esa.int/opensearch/description.xml",
					"type": "application/opensearchdescription+xml",
					"title": "search"
				}
			]
		}
	},

----

Corresponding JSON Schema:
----
		"Links": {
			"title": "Links",
			"description": "OGC 14-055r2",
			"type": "object",
			"properties": {
				"type": {
					"type": "string",
					"enum": [
						"Links"
					]
				}
			},
			"patternProperties": {
				"^(profile|alternate|via|icon)$": {
					"description": "OGC 14-055r2",
					"type": "array",
					"minItems": 1,
					"items": {
						"$ref": "#/definitions/Link"
					}
				},
				"^(search|describedby|related)$": {
					"type": "array",
					"minItems": 1,
					"items": {
						"$ref": "#/definitions/Link"
					}
				}
			},
			"additionalProperties": {
				"type": "array",
				"minItems": 1,
				"items": {
					"$ref": "#/definitions/Link"
				}
			}
		},
----

----
                "Link": {
			"description": "OGC 14-055r2",
			"type": "object",
			"properties": {
				"href": {
					"type": "string",
					"format": "uri"
				},
				"type": {
					"description": "MIME type",
					"type": "string"
				},
				"title": {
					"type": "string"
				},
				"length": {
					"type": "integer",
					"minimum": 0,
					"exclusiveMinimum": true
				},
				"lang": {
					"description": "RFC-3066",
					"type": "string"
				}
			},
			"required": [
				"href"
			]
		}

----

**Comment by cportele** [comment]
When I created the link object in WFS 3.0 I did not choose that pattern for two reasons:
* an additional level of nesting (due to the array to support multiple links for the same link relation);
* this basically makes the `rel` property mandatory, but `rel` is optional in RFC 8288 which is the conceptual basis.

That said, for the mandatory links we already require `rel` to be present.

If we would end up going in that direction, I would argue that we should adopt [HAL](https://tools.ietf.org/html/draft-kelly-json-hal-08) as we would be getting already dangerously close to it and it would be getting harder and harder to argue why we invented our own JSON approach to hypermedia. That would have quite some impact (e.g. the use of `_embedded`), so I am not sure whether we are too late for such a change, at least for OGC API Features / STAC / etc.

This would have to be resolved at the hackathon and the subsequent Leuven SWG meetings at the latest.

**Comment by rmam-spinworks** [comment]
+1 on HAL.  The document format is quite a treat to use, both as a consumer and as a producer. The suggestion has been covered in a separate issue (see #24).

**Comment by cportele** [comment]
20-MAY-2019 Conference call (OGC API Features): Both the current encoding and the HAL encoding are implementations of RFC 8288 (Web Linking). Since we are close to finalizing the specification and no concerns have been raised before, we would prefer to stick to the current encoding, that has been used in many implementation already.

**Comment by akuckartz** [comment]
In case this is revisited in the future: please consider using JSON-LD.

**Comment by ycespb** [comment]
I agree with the recommendation to consider JSON-LD. Ideally, the JSON encoding could be a compactation of the JSON-LD representation via a @context.  This would cover both JSON and JSON-LD use cases.

For example:
----
                       "iana:enclosure": {
				"@id": "http://landsat-ds.eo.esa.int/products/LANDSAT_ETM/2000/01/07/LS07_RMPS_ETM_GTC_1P_20000107T111229_20000107T111258_003886_0205_0031_9261.ZIP",
				"@type": "atom:link",
				"dct:title": "Download",
				"atom:type": "application/x-binary"
			},
			"iana:icon": {
				"@id": "http://landsat-ds.eo.esa.int/metadata/LANDSAT_ETM/2000/01/07/LS07_RMPS_ETM_GTC_1P_20000107T111229_20000107T111258_003886_0205_0031_9261.BP.PNG",
				"@type": "atom:link",
				"dct:title": "Quicklook",
				"atom:type": "image/png"
			},

----

**Comment by rmam-spinworks** [comment]
In case OGC API's approach to HATEOAS is revisited, here's a small review of the hypermedia specifications currently available to REST APIs:

* JSON HAL ([link](https://tools.ietf.org/html/draft-kelly-json-hal-08))

* JSON-LD ([link](https://json-ld.org/)) and variants such as Hydra ([link](http://www.markus-lanthaler.com/hydra/))

* Web linking through `Link` HTTP headers ([link](https://tools.ietf.org/html/rfc8288))

* Collection+JSON ([link](http://amundsen.com/media-types/collection/format/))

* JSON:API ([link](https://jsonapi.org/))

* Siren ([link](https://github.com/kevinswiber/siren))

**Comment by m-mohr** [comment]
Having it in the HTTP headers only works in HTTP context. If you have a static catalog as it is available in STAC for example, you don't necessarily have HTTP headers to hold your links. So, I think having it in the JSON document makes sense and we should keep it in the document in an extensible way (i.e. allow adding custom properties), not the way JSON:API does it.

**Comment by rob-metalinkage** [comment]
Have created a generic issue #135 to consider implications of JSON-LD in general.

**Comment by rob-metalinkage** [comment]
it is worth noting the status of these mechanisms

JSON HAL - informational 
JSON-LD - W3C Rec 
Web linking through Link HTTP headers (link) - IETF 
Collection+JSON - (just a proposal?)
JSON:API  (de-facto standard - widely implemented but stalled? 2015 statement that compliance testing for claimed implementations was planned..
Siren (proposal)

I'd rather choose and standardise an elegant proposal that adopt a borked standard - but in this case it seems JSON-LD in combination with domain data models allows us to simply embedded links, and link them to as much definition and annotation, in as many forms as you like, as required.

If you want to link to things, be prepared to declare the semantics of both your data and the link and use the appropriate mechanism to do so. The fallback is ad-hoc attributes and the current state of RTFM if you want to understand what such attributes mean.

**Comment by joanma747** [comment]
I'm not sure what is the proposal here. Is there any problem with the current links approach that makes it not compatible with JSON-LD?. (in my experience with JSON-LD, the model proposed at the beginning of the issue will generate a natural conversion to JSON-LD. Is this the actual issue?)

**Comment by joanma747** [comment]
See this other one (provided by @cportele)
https://datatracker.ietf.org/doc/draft-pot-json-link/

The MAIN problem for going into a different direction is the "incompatibility" with "OGC API Features v1.0".

NOTE: we are not imposing any format for the payload of the API (the data and content links). Only the API "mechanics".

The group discussing this issue the 2020/05/11 decided that the arguments above and enough to close the issue unanimously.
