### ISSUE TITLE
Make use of HTTP headers

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#28]
See https://github.com/opengeospatial/ogc_api_coverages/issues/9

There is a need to be able to over-ride some HTTP headers using query parameters (ex. -f for accepts header).  The headers which can be over-ridden and corresponding query parameters should be the same for all OGC APIs.  So we need to capture them in common.

**Comment by cportele** [comment]
I do not think that Common should specify query parameters to use in all OGC API specs. This can be left to the implementations. At least this is what we decided for the Features spec.

See http://docs.opengeospatial.org/DRAFTS/17-069r1.html#encodings and the discussion in https://github.com/opengeospatial/WFS_FES/issues/12.

**Comment by ycespb** [comment]
FYI: OASIS searchRetrieve uses the "httpAccept" query parameter to override the HTTP Accept header : http://docs.oasis-open.org/search-ws/searchRetrieve/v1.0/os/part3-sru2.0/searchRetrieve-v1.0-os-part3-sru2.0.html#_Toc324162475

**Comment by pebau** [comment]
A precise definition of format encoding is provided in OAPI Coverages Section 3.4, maybe that is worth looking at for OAPI Common.

**Comment by dstenger** [comment]
> I do not think that Common should specify query parameters to use in all OGC API specs. This can be left to the implementations. At least this is what we decided for the Features spec.
> 
> See http://docs.opengeospatial.org/DRAFTS/17-069r1.html#encodings and the discussion in opengeospatial/WFS_FES#12.

But, if we do not specify a default behaviour (e.g. mime type must be definable via HTTP Accept header), how do clients know how to access different representations of landing page, api definition, conformance classes and collections?
At least, when "OGC API - Features" spec is considered, it is not mandatory to provide links to all different representations of api definition, conformance classes and collections on landing page.
So, shouldn't there be a convention that HTTP Accept header is always considered by service implementation?

**Comment by cmheazel** [comment]
@dstenger I believe that we do require support for HTTP Accept. I will double check to make sure. The issue is whether we should allow an API to override the Accept Header using a query parameter (such as -f). The consensus appears to be that while it's not explicitly excluded, we discourage the practice.

**Comment by dstenger** [comment]
I agree.
However, if the behaviour is left to specification, as currently defined in features spec, how does a client, for example, request JSON encoding of: `GET http://server/oapi/collections?f=html`?
Adding HTTP Accept header does not have an effect and the `f=html` mechanism is not defined by specification.

**Comment by joanma747** [comment]
The server is in control of the links so the server makes available public with the modifiers necessary to use it in contexts with on content negotiation is not available. The API definition can expose the f= parameter as well as the "following the links".

http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#encodings

This is the text that we will recicle in OGC API Common:

> Note that any server that supports multiple encodings will have to support a mechanism to mint encoding-specific URIs for resources in order to express links, for example, to alternate representations of the same resource. This document does not mandate any particular approach how this is supported by the server.
> As clients simply need to dereference the URI of the link, the implementation details and the mechanism how the encoding is included in the URI of the link are not important. Developers interested in the approach of a particular implementation, for example, to manipulate ("hack") URIs in the browser address bar, can study the API definition.
> 
> Note | Two common approaches are:     
> * an additional path for each encoding of each resource (this can be expressed, for example, using format specific suffixes like ".html"); 
> * an additional query parameter (for example, "accept" or "f") that overrides the Accept header of the HTTP request.
> 
> 
>

**Comment by rob-metalinkage** [comment]
Note there is now a canonical mechanism for doing this available (and implemented in the OGC definitions server) 
https://github.com/w3c/dx-connegp

note - if you only have one profile available you can get away with Accept headers. CNEG p however provides a "follow the link" option that Headers dont directly support.

**Comment by cmheazel** [comment]
Add this text to API-Common Core.
See Features issue #12 for background.
Action: Make this change and re-visit next week.

**Comment by cmheazel** [comment]
No change necessary. The text was already there.
