### ISSUE TITLE
Should OGC API: Common mandate any CRS?

### ISSUE THREAD

**Issue by nmtoken** [opengeospatial/oapi_common#30]
WFS 3.0 / OGC API - Features (core) mandates the support of WGS84 lon/lat for all output formats.  Should the same mandate apply to OGC API: Common to be inherited by the other OGC APIs?

My hope is that no CRS will be mandated in  OGC API: Common, the common position should be that native CRS is supported.

**Comment by cmheazel** [comment]
@nmtoken see https://github.com/opengeospatial/WFS_FES/issues/233
I believe there needs to be a default. We can't assume that the developer knows anything about spatial data. We can end up with an API that mixes data from different CRSs (yes it does happen). What is missing is a way for the API to specify a default other than CRS84.

**Comment by nmtoken** [comment]
I can see the point for an instance of an API having some mechanism to define a default, which would/could be part of OGC common specification (the mechanism for defining it) so you might have a lunar WFS instance that defaults to a lunar projection and I might have a Martian WCS instance that defaults to a Martian CRS, but I don't think that common should go as far as saying the default will be CRS:84, just possibly that there will be a default.









Perhaps, the default will be CRS:84 unless you

**Comment by rmam-spinworks** [comment]
> but I don't think that common should go as far as saying the default will be CRS:84

Specifying a default CRS ensures that all implementations support at least a common CRS, which I believe is necessary to guarantee interoperability.

**Comment by cmheazel** [comment]
The collectionInfo metadata (returned for each collection) allows you to specify the CRS supported by this collection. It also says "the first item is the default coordinate reference system." So we can establish CRS:84 as the default. The API can change that default. The client can specify one of the other CRS if they don't like the default. All good.

**Comment by jyutzler** [comment]
Is there any reason this is still open? It appears to be settled.

**Comment by nmtoken** [comment]
So it's not in core, because collections is no longer in core?

**Comment by cmheazel** [comment]
@nmtoken correct. None of the resources in Core have spatial coordinate. Please look at Part 2 (August 2020 branch) to make sure we have this issue covered.

**Comment by ghobona** [comment]
2020-08-24 SWG telecon.

@cmheazel To merge the August branch to Master.
