### ISSUE TITLE
relation "item" / "items"

### ISSUE THREAD

**Issue by ycespb** [opengeospatial/oapi_common#33]
The "buildings" example in the "core" uses rel="items" in the /collection/{collection-id} response example while this should be "item" ?  Only "item" is a registered iana relation and WFS 3.0 uses also "item" instead of "items" ? Can you confirm the correct relation to use ?

**Comment by cportele** [comment]
@ycespb - "item" was used in draft.1 of WFS 3.0. The latest OGC API Features draft uses "items", so "items" is correct. 

See also http://docs.opengeospatial.org/DRAFTS/17-069r1.html#_link_relations and http://docs.opengeospatial.org/DRAFTS/17-069r1.html#example_4.

**Comment by ycespb** [comment]
Ok Thanks.  "items" is not yet in the list at https://www.iana.org/assignments/link-relations/link-relations.xml but I assume this will be taken care of.

**Comment by cportele** [comment]
Yes, as stated in http://docs.opengeospatial.org/DRAFTS/17-069r1.html#_link_relations, there are three link relations that we use, but that are not yet registered. For registration we need a spec reference, so the idea is to (try to) register them, once the standard is approved.

**Comment by cmheazel** [comment]
API-Features addresses this issue. API-Common is in-line with API-Features. This issue can be closed.
