### ISSUE TITLE
identify useful shortnames for API types

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/oapi_common#35]
From WFS_FES Gitter:

>Just van den Broecke @justb4 06:34
Q: I see that OGC has rebranded/renamed WFS3 to "OGC API - Features". Will the term "WFS3" be completely abandoned? And will there be an abbrev like OAF? "OGC API - Features " is quite a mouthful..

>Tom Kralidis @tomkralidis 06:35
good point @justb4. Overall we definitely need short code names to be able to delineate API types easily in code.

**Comment by ghobona** [comment]
@tomkralidis, @cmheazel,  @cportele,

This issue has now been moved to the opengeospatial/oapi_common repository.

**Comment by tomkralidis** [comment]
Options:

1.
- `OGC:API:Features`
- `OGC:API:Coverages`
- `OGC:API:Processes`
- `OGC:API:Records`
- `OGC:API:MapsTiles
`

2. should we consider `OGC:API` and then let interaction with conformance figure out the rest?

3. Something else?

**Comment by ghobona** [comment]
Here are the shortened names suggested by the OGC's Communications office:

* `OACom` short for OGC API - Common
* `OACov` short for OGC API - Coverages
* `OAFeat` short for OGC API - Features
* `OAPro` short for OGC API - Processes
* `OAMT` short for OGC API - Map Tiles

NOTE: OGC API - Map Tiles is currently also referred to as OGC API - Maps and Tiles. We expect the SWG will settle on a name within the next few months. This may lead to a separate `OAMap` for maps.

**Comment by m-mohr** [comment]
> Here are the shortened names suggested by the OGC's Communications office:
> 
> * `OACom` short for OGC API - Common
> * `OACov` short for OGC API - Coverages
> * `OAFeat` short for OGC API - Features
> * `OAPro` short for OGC API - Processes
> * `OAMT` short for OGC API - Map Tiles

Is this official/final or will this change? I'm just wondering what I can use in other non-OGC specification texts.

**Comment by pvretano** [comment]
Because,  definition -> oaf /ōf/, noun : a stupid, uncultured, or clumsy person

**Comment by m-mohr** [comment]
Fair enough. Although OAF would be uppercase and I wouldn't think of that word. Also, I think people would say the letters individually (oʊ eɪ ɛf) and not ōf. OAF (and all the others) are just easier to type and to say. I'd even prefer the ones suggested by the OGC's Communications office over OAPIF etc.

**Comment by tomkralidis** [comment]
Suggestions/additions:

- change `OAPro` to `OAProc` (`OAPro` sounds like upgrading to a better software version?)
- add `OARec: OGC API - Records`

**Comment by jerstlouis** [comment]
I would not think it an essential priority to reference loose grouping of functionality, organized in a very classic OWS way, and not recognizing the fact that actual server capability and functionality may cross the classic services boundaries.

Sticking to "OGC API" would encourage building integrated and modular APIs. When needed,  specific conformance classes or modular grouping of them can be referenced, but it seems to me that trying to stick to directly mapping 3 letter acronyms directly results from a fear of stepping away from classic OWS into the promising new modular world, where building blocks can be mixed & matched:

Vector Features + Coverages + Tiles + Processes + Maps (server-side rendering)

When I use all of these integrated capabilities from a single request to a single end-point, I am not using 5 different OA* APIs, I am using an OGC API to perform the (complex) operation I need to.

**Comment by cmheazel** [comment]
The OGC NA is setting policy on this issue.
