### ISSUE TITLE
Relationships between resources in Web APIs

### ISSUE THREAD

**Issue by cportele** [opengeospatial/oapi_common#39]
How do we express relationships between geospatial resources shared on the Web? For example, that a feature collection, a coverage and a map are different resources based on the same data. 

OGC has struggled with this for a long time and the OGC Web Services standards never had a good answer. It would be good, if the OGC API standards would find consistent ways to express such relationships.

There are (at least) two mechanisms in the OGC API context:

* Resource hierarchy: If all the resources are shared via the same API, some relationships (like the one from the example above) can be expressed through the resource hierarchy:
  * /collections/{collectionId} - information about the data
  * /collections/{collectionId}/items - the features
  * /collections/{collectionId}/coverage - the coverage 
  * /collections/{collectionId}/map - the map
* Typed links: We can express relationships though links in the `links` member of the resource. At a minimum we would need guidelines on the link relation types to use for which cases. The [currently registered link relation types](https://www.iana.org/assignments/link-relations/link-relations.xml) seem insufficient. For example, `related` is very generic. How do we type the link between the feature collection, the coverage and the map, if they are shared via separate APIs?

This issue was discussed in a WFS SWG call by @pvretano, @cmheazel and @cportele based on [an issue in the Features repository](https://github.com/opengeospatial/WFS_FES/issues/249), which is not an issue for the Features specification, but the general OGC API architecture and should be discussed in Common.

**Comment by akuckartz** [comment]
> For example, that a feature collection, a coverage and a map are different resources based on the same data.

Such information can be encoded using RDF triples / Linked Data.

**Comment by cmheazel** [comment]
Discussions on this issue have continued in other threads.  Has this issue been addressed?

**Comment by dblodgett-usgs** [comment]
This issue has been settled in #140.
