### ISSUE TITLE
Include collections or resources as part of the common

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/oapi_common#4]
I was surprised when the initial set of "bits" where imported into the OAPICommon. I was convinced that we were going to include "collections" as part of the commons but I believe we have not at this point.

Do we need collections to be included in OWS common as the equivalent to "dataset"?. It seems something that is common in WFS, WMS WMTS, SOS and WCS  (if you consider that the coverage is the collection itself. How this fits with WPS?.

**Comment by cportele** [comment]
For a common Core we will need to have dataset + collections as an additional conformance class as some resources are not dataset-related (e.g. processes, styles).

**Comment by cmheazel** [comment]
Both the collections metadata as well as collections is included.  Collections is a small bit after collections metadata but before parameters.

**Comment by pvretano** [comment]
Generally I think that "collections" would be part of common but there are exceptions.  WPS is one such case and I think that is fine.

I imagine that OGC API Common will include stuff the must be included in a another specification that references it (such as / or /api or /conformance) and then other parts that, if required by the referencing specification, must be done as described in OGC API Common.  Datasets (i.e. collections), the definitions of the bbox parameter, the definition of the time parameter, some general query syntax (e.g. CQL) are all examples of stuff that would be defined in OGC API Common but would not be mandatory.

In the case of WPS, in TB14 and in the WPS SWG (I believe) there is no "collections" path.  That is not to say that datasets might not be part of a WPS but that is a very implementation specific thing.  There might be a WPS that offers a library of processes that operate with a specific dataset(s) but there may also be a WPS that offers a library of stand-along processes with no related to any dataset.
  
F.Y.I. The current set of WPS paths is (at least in the EOC thread from TB14)

/
/api
/conformance
/processes
/processes/{processId}
/processes/{processId}/jobs
/processes/{processId}/jobs/result

**Comment by cmheazel** [comment]
There is a proposal within the OpenAPI TSC of creating a new JSON Overlay standard.  This would be an x-link type of structure that points into another JSON document followed by the content to patch into that document at the designated location.  

Now consider WFS, WCS, WPS as overlays.  They don’t have to address any of the OAPI common stuff.  They just need to identify where they extend OAPI common and provide the new content.  

Under this model, /collections becomes a target for the overlay "x-link".

Note: this could also work for extensions.

**Comment by pvretano** [comment]
@cmheazel Before I go hunting, do you happen to have the links to the OpenAPI proposal handy?

**Comment by cmheazel** [comment]
Peter,

Don’t go hunting, you won’t find anything.

This has been discussed in several OpenAPI issues but is not captured in a single, documented proposal.  What I do have is a presentation from the December 18 TC  which includes a description of the proposal.  The concept has evolved a bit since then, but the basic concept is the same.

This is a feature I’m willing to push in the OpenAPI TSC if we think it is important.

Chuck

**Comment by cmheazel** [comment]
@cportele  There was quite a bit of discussion within the TSC about that. Mostly about which option was most mature and likely to win-out in the long run.
In addition to the path, we should be able to specify the operation (insert, replace, etc).

**Comment by rhattersley** [comment]
> Generally I think that "collections" would be part of common but there are exceptions. WPS is one such case and I think that is fine.

As well as processes, the hackathon back-briefs have just identified use cases for coverages (& maps?) where there is no need for collections, e.g. `/coverages` and `/coverages/{coverageid}` coming directly from the root.

cc: @cmheazel

**Comment by cmheazel** [comment]
Common specified collections as a separate Conformance Class from Core.  This makes is an API Module. Derived standards can use it of not as appropriate. Recommend closing.
