### ISSUE TITLE
Items?

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#45]
CREAF comment from the API Hackathon report:

The OGC API - Features specification defines a collection as a set of 'items' (a.k.a features). During the hackathon it became clear that the concept of "collection" needs to be generalized to any type of data type, for example coverages. After the hackathon, the discussion continued and it was proposed that, in some cases, the very same collection could be requested as features, a coverage, a map, etc.

**Comment by cmheazel** [comment]
UK Met Office comment from API Hackathon ER:

In the WFS3.0 spec, /Items/ needs to be replaced by 'point', 'timeseries', trajectory', etc. This is
consistent with the approach advocated by Joan Maso, of CREAF, for maps and tiles.

**Comment by cmheazel** [comment]
Discussion continued in #74

**Comment by cmheazel** [comment]
The current (5/11/2020) version of API-Common-Collections should address this issue.  Recommend to be closed.

**Comment by dblodgett-usgs** [comment]
This issue has been settled in #140.
