### ISSUE TITLE
Add Collection Type to the response

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#46]
From the API Hackathon report:

Eurac Research proposed the direct use of the path /collections/{collectionid}/{coverageid}
instead of the path /collections/{collectionid}/coverages. The reason being that if collections can
have different types of collections e.g. a feature collection and a coverage collection, it may be more appropriate that this information is delivered in the metadata of the collection with a type field.

**Comment by joanma747** [comment]
Collections should be made able in different representations: coverages, maps, items...

The way to know which types are able is to read the links in collections/{collectionId}

CollectionType be redundant and will move us further from the "follow the links" approach.
