### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#48]
From API Hackathon Report:

The specifications do not include "keywords" currently. Ideally this should be mandatory in core
to facilitate discovery. While popular search engines may not currently use this field, that does
not mean they and/or others would not in the future. GeoSeer does use this field for indexing,
and many current OGC Web Services have this set with meaningful keywords by their
deployers. GeoSeer would suggest having it both at the root level (to indicate the type of
"service"), and at the /collections level for each collection. This would improve discoverability.

**Comment by bradh** [comment]
While I agree, the Features API does not include this and the editors considered it to be appropriate for an extension.

**Comment by cmheazel** [comment]
@bradh The only issue I have is that automated systems are very bad a generating keywords. The result is that all of the data they produce has the same keywords. Not very useful.

**Comment by bradh** [comment]
Again, agree. I think the middle ground is to have the mechanism specified in Common, but not to mandate that any values be present. If the implementation wants to provide them, then they provide them as `"keywords": ["blah", "whatever"]` where the key and value parts are to be defined, but equally its OK for that not to be available if there is no meaningful content (i.e. don't show me "geospatial" and "data" for my keywords).

**Comment by joanma747** [comment]
See the implementation of keywords and other elements here:
https://github.com/opengeospatial/OGC-API-Map-Tiles/blob/master/standard/openapi/ogc-api-common.yaml (a work done by Testbed 15 and WMS.SWG

**Comment by m-mohr** [comment]
STAC has a keywords field in their collections. STAC Collections base on OGC API - Commons/Features collections and therefore ideas/definitions from there could simply be re-used: https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md

**Comment by joanma747** [comment]
Metadata will be addressed in the guide and not in part 1. Decided in 2020-09-28 telco.
