### ISSUE TITLE
Reinventing the wheel?

### ISSUE THREAD

**Issue by hylkevds** [opengeospatial/oapi_common#5]
While OpenAPI is a really nice "invent your own API"-API, is there really a need to invent our own API?

There are existing REST-API standards, like [OASIS OData](https://www.oasis-open.org/committees/odata/), that I'm pretty sure, cover 99% of OGC needs, and that are mature, established standards.
They have already nailed down nasty things like data types, encoding, filtering, property selection, method invocation, collections, pagination, etc., etc...
It seems to me that it would be much more efficient to apply such a standard to our data models, than to re-specify all those little details all over again.

**Comment by ruimaciel** [comment]
@hylkevds OData is a standard that specifies how to create a particular style of RESTful APIs, and also serves as a target to develop ancillary tooling, but it still leaves developers with the job of actually specifying the APIs, which AFAICS it's what's being done at this stage.

**Comment by akuckartz** [comment]
Really RESTful API would help. But I do not agree that OData provides that. 

I strongly agree with this: https://ruben.verborgh.org/blog/2013/11/29/the-lie-of-the-api/

**Comment by cmheazel** [comment]
Ruben seems to be using another definition of API.  
The API approach we are using is built on hypermedia navigation and URLs. The API is not a separate interface. It is the information you may want to efficiently navigate the hypermedia. For instance, a straight hypermedia approach will not tell you the valid values for query parameters, security restrictions, valid encoding types, etc. We provide that information through the OpenAPI document, /conformance resource, and by standardizing how the hypermedia paths are constructed. If you already have that information, then go straight to the resource. If you are new to the API, then the information you need is easy to find.

**Comment by hylkevds** [comment]
> @hylkevds OData is a standard that specifies how to create a particular style of RESTful APIs, and also serves as a target to develop ancillary tooling, but it still leaves developers with the job of actually specifying the APIs, which AFAICS it's what's being done at this stage.

Yes and no. With OData you still have to create a _data model_, but the _API_ automatically follows from that. Once you've identified a collection with entities, you can, for instance, automatically apply:

- [Addressing the Model for a Service](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_AddressingtheModelforaService) Essentially similar to the OpenAPI API definition
- [Addressing Entities](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_AddressingEntities) How to address collections and entities
- [pagination](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_SystemQueryOptionstopandskip) Every API that has collections needs pagination
- [Accessing linked entities](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_AddressingtheCrossJoinofEntitySets) How to access linked entities
- [Filtering on all defined properties of those entities](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_SystemQueryOptionfilter) No need to separately state that you can filter on time or using bounding boxes. What if the entities have no time or geometry? or multiple?
- [In-Lining linked entities](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_SystemQueryOptionexpand) 

OpenAPI doesn't help with specifying how to do these things like pagination, filtering, entity-in-lining, etc. So every OpenAPI API has to re-specify these things, and every OpenAPI API does it differently...

These things do seem to be duplicated here too. [REQ_fc-time-definition.adoc](https://github.com/opengeospatial/oapi_common/blob/master/OAPI-Common/requirements/core/REQ_fc-time-definition.adoc) specifies a filter parameter for time... To me that is a superfluous requirement. If an entity has a time property, one should be able to filter based on that property. When applying a good API standard, how to do that filtering is implicit.

**Comment by ruimaciel** [comment]
@hylkevds even by your own definition, the API is still being defined by creating the data model. OData only specifies a certain style of RESTful API, and also enables third-parties to develop tooling that helps developers implement the API by simply plugging in a data model.

Nevertheless, you're conflating a standard that helps developers create their own APIs following a particular style (OData) with the task of actually specifying a collection of APIs.  Even if we argue that the conceptual models of some OGC standards are enough to provide OData-based encodings for said standards, those encodings would still need to be validated and specified.  Even so, I believe that this standardization push also includes updates changes to the old conceptual models, which would negate this argument.

**Comment by hylkevds** [comment]
I'm saying that _the task of actually specifying a collection of APIs_ is made a lot lighter if one applies existing standards for APIs in those places where it makes sense, instead of completely inventing new APIs from the ground up, even if one uses API-Description-APIs to describe those new APIs.

Designing a data model and then applying an API standard is potentially a lot less work than designing a data model AND designing an interface for it. Just because OData (and friends, OData is not the only option) doesn't cover everything does not negate the fact that it can cover a lot of the boiler plate of new APIs that need a rest-like interface.

**Comment by cmheazel** [comment]
Overcome by events.

**Comment by hylkevds** [comment]
I'd say it is still very relevant. There are still plenty of wheel that seem to be in the process of being re-invented. Filtering for example...

**Comment by cmheazel** [comment]
@hylkevds I agree that we should reuse instead of reinvent.  However, the essence of this thread is whether we should base our APIs on OData. That decision has been made across the Web API SWGs. Future discussions of reuse need to take place in their own issues. That keeps the discussion focused on a particular capability and is much more likely to lead to a resolution.
