### ISSUE TITLE
Coverages and Collections

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#53]
From the API Hackathon ER

GeoSolutions' participation in the separate thread has been focused on the Coverage API. As others have noticed, the current approach of treating the "collection" as a possibly heterogeneous set of coverages (e.g., accessing a single coverage via collection/{collectionId}/coverages/{coverageId} raises some doubts in terms of practical usage of the service for the simpler cases. There are evident needs of supporting different use cases, including:

• Simple standalone raster datasets, or composite raster datasets that can be seen, from the eyes
of the users, as a single seamless coverage
• Stitched mosaics where the mosaic/collection can still be managed as a coverage of its own,
while giving users access to its internal composition
• Ensembles/heterogeneous collections where multiple coverages with different physical
phenomenon, bands, resolutions are stored, allowing grouping by intended usage, but lacking
the possibility of considering the collection itself as a coverage

GeoSolutions believe the subdivision of these use cases in a core specification and extension likely merits some further discussion, involving parties from both API Common and the coverages API.

**Comment by joanma747** [comment]
See https://github.com/opengeospatial/ogc_api_coverages/issues/28

**Comment by cmheazel** [comment]
If there are no additional comments, recommend to be closed.
