### ISSUE TITLE
OpenAPI

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#55]
From the API Hackathon ER:

(Jacobs) Additionally, some basic concepts need to be defined more clearly, see issues in the OGC API - Coverages repo [https://github.com/opengeospatial/ogc_api_coverages]:
• 1 [https://github.com/opengeospatial/ogc_api_coverages/issues/1]: OpenAPI basics: what does "/" mean? (closed while not resolved),
• 3 [https://github.com/opengeospatial/ogc_api_coverages/issues/3]: Path syntax (closed while not resolved)
• 19 [https://github.com/opengeospatial/ogc_api_coverages/issues/19]: identifier syntax for OAPI Common

**Comment by cmheazel** [comment]
From the API Hackathon ER:

mixed use of path components - in the URL
/collections/{collectionId}/coverages/{coverageID}/rangetype the path component "collections" is
a fixed keyword; "{collectionid} is an identifier in the service offering, whereby the pair
"collection and "collectionid" always must appear (i) at that position in the path and (ii) in that
sequence; "rangeType" is a function that extracts part of a coverage. Hence, a path component
can be a keyword, an identifier, or a function. In the case of a function, in the case of
"rangetype" the function input is the left-hand side, but it is not clear that this is always so.
Additional parameters are only possible in the query part, and this query part constitutes one
single pool of arguments where it needs extra effort to disentangle what parameter belongs to
what function.

**Comment by cmheazel** [comment]
From the API Hackathon ER:

(Jacobs) there is a one-level collection concept, ie: every service must offer a collection of items, which cannot contain other collections. It remains unclear why variable-depth collections are not
supported (although they have been discussed).

**Comment by cmheazel** [comment]
From the API Hackathon ER:

(Jacobs) establish a clear semantics for the basics of OpenAPI use in OGC - a task for OGC API - Common.

**Comment by jyutzler** [comment]
There are a lot of details in this ticket, but as far as I can tell they have all been resolved. I recommend closing this.

**Comment by cmheazel** [comment]
Concur.
