### ISSUE TITLE
Content Negotiation

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#57]
The NGA developers at the API Hackathon made multiple recommendations for improving how OGC APIs perform content negotiation.  While the comments were directed at API-Features, they need to be addressed in Common.

**Comment by bradh** [comment]
To be actionable, this ticket needs to identify the recommendations. 

Content negotiations is possibly (partly?) covered at #28

**Comment by cmheazel** [comment]
@bradh Agree. 
The recommendations are in section A.21.4 of the API Hackathon Engineering Report. A bit too much content to put into a GitHub issue. I've asked Gobe to release a draft of the ER to the OWS-Common SWG.
