### ISSUE TITLE
Mixed Hyperlink Representations

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#59]
Spacebel comment from the API Hackathon ER

The approach to represent hyperlinks in JSON is unfortunately different from the encoding
proposed by OGC 14-055r2 which means that an OpenSearch implementation based simultaneously on OGC 14-055r2 and OGC 17-047 in combination with OGC API Common will have different encodings for links in search responses and in other resource representations (e.g. /conformance, /etc).

**Comment by joanma747** [comment]
See this document for more details about this: https://github.com/opengeospatial/architecture-dwg/blob/master/json-best-practice/clause_9-LinksinJSON.adoc
I'm not sure if we will be able to get consensus on this one. I personally have gave up.

**Comment by jerstlouis** [comment]
Potentially this is also related to https://github.com/opengeospatial/oapi_common/issues/160 ?

**Comment by cmheazel** [comment]
It may be related, but I don't see how this issue adds anything to 160. There is no reason to keep it open.
