### ISSUE TITLE
JSON Schema vs. OpenAPI 

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#61]
Spacebel comment from API Hackathon ER

Making (JSON) data models available as separate JSON Schemas (https://swagger.io/docs/
specification/data-models/keywords/) and not mixing them with actual OpenAPI descriptions (but
refer to them) would allow validating JSON representations separately with JSON schema
validation tools and before a service is put up.

**Comment by joanma747** [comment]
JSON Schemas and OpenAPI schemas are not so different and it is easy to take a JSON schema and embed it in Open API.
Anyway.
There are 2 ways to do this:
* Wait if OpenAPI spec to include it
* Create our own description of the API (I do not like this)
* Create a companion document to the OpenAPI with the schemas

Others?

**Comment by cmheazel** [comment]
The efforts by the OpenAPI TWG to integrate JSON schema into OpenAPI address this issue.
