### ISSUE TITLE
Unified API Standards

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#62]
Comment from Univ. of Munster in the API Hackathon ER

The university is of the view that OGC should not just make standalone specifications, but to
instead make them work together. This is not only having a common set of functionality with
OGC API - Commons, but using WFS ,WCS, WPS, and CAT in a single API. The university tried
this, unsuccessfully, with openEO for the previous versions of the standards. Therefore, the
university had to come up with non-OGC standards, especially for processing. So OGC should
make sure there is communication between the groups on how the standards can be used
seamlessly together!

**Comment by joanma747** [comment]
What do we need in practice to achieve this? Some suggestions
* A dataset should be retrievable in different spatial representations: features, coverages, maps... deriving from \collections\{collectionId}
* Some components should be applicable to several representations
* Somebody need to be vigilant to avoid repetition of components, contradictions, overlaps...
* ...

**Comment by jerstlouis** [comment]
In my opinion, this is by far the most valuable improvements that the OGC API specifications can bring over the classic OGC services. This is much line line with the proposal for this in #17, and OGC API - Common (Collections) attempts to define the fundamental building block to enable this.

**Comment by cmheazel** [comment]
The proposed approach has been adopted by the OGC.
