### ISSUE TITLE
Exception reports are too simple?

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/oapi_common#65]
I'm recording a Keith Pomakis comment on Testbed 15.

> I like the idea of introducing a JSON-based exception report that we can transition 
> to, but I think the examples of such an exception report in the Image 
> API description on swaggerhub are woefully inadequate:
> 
>    {
>      "code": "500",
>      "description": "An internal server error occured. Incident ID: 
> 1234567. Please contact admin@example.org."
>    }
> 
>    First, the code is redundant, since it's reported via the HTTP 
> headers.  Second, it lacks the very useful multi-level description and 
> language indicators that OGC Common exception reports have.  It also 
> lacks the OGC code and locator attributes of the OGC Common exception 
> reports.  I always found such codes to be an unnecessary nuisance 
> myself, but nonetheless they've been part of OGC exception reports for 
> decades.  Such matters need to be carefully considered when developing a 
> new JSON-based exception report schema.
> 
The current exception report comes from this schema:
https://raw.githubusercontent.com/opengeospatial/ogcapi-features/master/core/openapi/schemas/exception.yaml
Do we need to have some additional information as we had before in the common exceptions?

**Comment by cportele** [comment]
Note that the `exception` schema is not referenced from normative statements, i.e. it is informative and APIs may handle exceptions with different payload, too.

We have still included it as it represents a useful minimal practice that can be used as a starting point - and actually is pretty close to what many Web APIs do. 

To explain the design consideration behind the schema: Repeating the status code is quite common practice, whether the exception response is in html or json. An explanatory description (that typically hides any implementation details) is good practice. Anything beyond that should be implementation dependent and everyone is free to add additional information, but there should be no requirement or expectation that this is done by all implementations in the same way. 

OGC API is not just about a homogenous single OGC Web API, it is about building blocks for reuse and to extend in Web APIs.

Also, in my experience, exceptions that I have seen from existing OWS implementations are often not helpful and may not provide any actionable information. If OGC API implementations will consistently provide an actionable description, that would already be a step forward.

**Comment by cmheazel** [comment]
No additional comments since September 2019.  Recommend that this issue be closed.

**Comment by cmheazel** [comment]
NOUC: make sure Features and Common are aligned then close.

**Comment by cmheazel** [comment]
Confirmed that Features and Common are aligned.
