### ISSUE TITLE
Scope of Encoding Recommendation

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#67]
API Common recommends that an API implement HTML and GeoJSON encodings.  And it provides conformance classes for each.  You can find the supported encodings at the /conformance path.  This implies that we need to define conformance classes for all possible encodings.  Do we really want conformance classes for GeoTIFF, NITF, Protobuf, etc.?  Or should we limit the scope of these encodings to the resources defined in the standard itself (collections metadata, collection info, and possibly API Description)?

**Comment by cportele** [comment]
We (only) need a conformance class for an encoding, where consistency, conformance and testing of that encoding is important. An indicator could be that a "sufficient" number of client and server tools have implemented / public APIs are offering that encoding.

**Comment by cmheazel** [comment]
Division of API-Common into a family of standards addresses this issue.
