### ISSUE TITLE
"Objects" need a unique identifier

### ISSUE THREAD

**Issue by pebau** [opengeospatial/oapi_common#80]
"Objects" (understood as features, coverages, etc.) need to have a common identifier concept. Such an identifier

- should not be limited to syntax constraints like GML NCNAME (non-colon name) considering that URLs contain a colon
- should be worldwide unique (not just within a server offering), maybe using UUIDs

Related is: the result of an API call that modifies (extracts, processes, etc.) the information content of the original resource should receive a new identifier as it represents a different (new) resource in itself.

This mechanism should be best kept in Common so as to guarantee that users always perceive the same behavior across all OAPI-*.

**Comment by pebau** [comment]
PS: this calls for an opaque identifier, as opposed to human-understandable "names". (This bears resemblance to common database modelling techniques where entities stored receive an auto-generated id attribute.)

**Comment by cmheazel** [comment]
@pebau I agree 100%. But, this requirement would impact all OGC content standards.  I think this would be a TC issue and out of scope for the API-Common SWG.
