### ISSUE TITLE
collection type property name

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/oapi_common#81]
cc @schpidi

In https://github.com/opengeospatial/oapi_common/blob/master/standard/openapi/schemas/collectionInfo.yaml#L27 we describe `itemType` as `indicator about the type of the items in the collection (the default value is 'unknown').'`.

Given collections apply to other resource types (coverages, etc.), can/should we rename `itemType`?  Options:

- `type`
- `collection_type`
- other options?

**Comment by Schpidi** [comment]
see also #36

**Comment by joanma747** [comment]
I believe this discussion is clear in #36 and I'm closing this issue.
