### ISSUE TITLE
DOI for objects

### ISSUE THREAD

**Issue by pebau** [opengeospatial/oapi_common#84]
For better Findability we might add an (optional?) attribute DOI to first-class citizens like coverages and features. STAC supports DOIs already.

**Comment by joanma747** [comment]
items has their own id: {featureId} that is unique in the collection
Objects can be retrieved by URL: /collection/{collectionId}/item/{featureId}
that can be considered an id in the internet. Do we need another one?
At least in publications, DOIs are supposed to be unique and the URLs are just references and there can be many of them if the same object is available in different repositories.

We are starting to use DOIs for datasets (e.g. pangaea.de) but not for individual objects. But if you follow the OGC API features presentations there is only one dataset per server that is exposed as one or more collections. So there is a single DOI for the whole server?.

I'm a bit confused with so many id's; an it is not the first time I have this feeling.

**Comment by bradh** [comment]
DOI for a feature seems like an academic focus, and seems like an unneeded complexity.

**Comment by dblodgett-usgs** [comment]
I think this suggestion came up in the context of having one unique id for the "/collection/{collectionId}" that serves as an identifier for the data which may be available as items, a coverage, map tiles, etc. 

We were trying to make that point that conceptually, the OGC-API provides a set of interfaces to data that may or may not support particular OGC-APIs (features, coverages, etc.)
