### ISSUE TITLE
How to create new top-level resources

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/oapi_common#89]
OWS Common does not have to define new top-level resources such as "\processes" or "\maps" ... but it could provide some indication for the other standards groups to do so. This will prevent "collisions" of resources or defining "equivalent" new resources at different levels.

Actually OGC API maps and tiles defines \maps and \tiles when more than one collection is needed but  .../{collectionId}/maps when only one collection is involve. Is this a patters that we could 
generalize (just a wild example):
.../{collectionId}/process/buffer?param1=50  (for the far future of OGC API process?)
/processes/overlay?collections=map1,map2    (the near future of OGC API process)

**Comment by cmheazel** [comment]
@joanma747 Take a look at section 8.4 Information Resources.
