### ISSUE TITLE
Rename OGC API-Common

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/oapi_common#90]
The OAB recommends that OGC API-Common be renamed to OGC API - Common - Part 1: Core.  This will align the name of API-Common with the other API standards.

**Comment by chris-little** [comment]
Agreed, but being an OAB member, I would say that!

**Comment by jeffharrison** [comment]
So then the OGC API - Common would, presumably, have Extensions?

**Comment by cmheazel** [comment]
Yes.  OGC API extensions which are used by more than one API standard would reside in Common.  Each would have it's own conformance class.

**Comment by jeffharrison** [comment]
So if folks where to agree on how to define and use collections (if they agree) then it could be in an Extension to Common since it could be presumably usable by more than one API standard (?)

Best Regards,
Jeff

**Comment by cmheazel** [comment]
The name has been changed OGC API - Common - Part 1: Core in the March-2020-Updates branch.

**Comment by chris-little** [comment]
@cmheazel I support the name change. Happy for a merge of the branch. Will the change cascade down to the EDR API candidate-specification, or do I have to do a copy and paste?

**Comment by cmheazel** [comment]
Name change will be applied once some typos have been corrected.

**Comment by ghobona** [comment]
Pull Request created with renaming fix https://github.com/opengeospatial/oapi_common/pull/141

**Comment by cmheazel** [comment]
Merged and closed
