### ISSUE TITLE
Does /req/core/root-success allow for HTTP redirects?

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/oapi_common#98]
Text suggests not - but it seems at odds with Web architecture. Suggest reword to make it explicit that redirects are allowed.

**Comment by cmheazel** [comment]
The current version (as of 5/11/20) should make it clear that nothing in these standards preclude use of legal HTTP features. To state that a specific feature is explicitly allowed would imply that some features are not allowed.  
@cmheazel to re-visit the general requirements to make sure we do not violate this principle.

**Comment by cmheazel** [comment]
Section 8.3.1 - remove "strongly" and "both" from paragraph 2.  Add status code 303. 303 is not a success for purposes of conformance testing.  Add a few words about what 303 is. 

Also add 302 - same expected behavior as a 303

**Comment by cmheazel** [comment]
Added codes 302 and 303.
Neither 302 nor 303 return the requested resource. Nor do they guaranty that the resource can be retrieved. Therefore, neither of these codes are acceptable as evidence that an operation has been successfully completed.
